CUDA_VISIBLE_DEVICES=0 \
swift rlhf \
    --rlhf_type dpo \
    --model /path/to/your/reference_model \
    --train_type lora \
    --dataset ./data/dpo_train.jsonl \
    --torch_dtype bfloat16 \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 1e-5 \
    --lora_rank 8 \
    --lora_alpha 16 \
    --target_modules q_proj k_proj v_proj o_proj \
    --gradient_accumulation_steps 4 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 5 \
    --max_length 1024 \
    --output_dir /path/to/save/results \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 1 \